### ISSUE TITLE
Error Message Popup Verification in Multi-Download Option

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#1]
Steps To Reproduce:
1. Do not select any plugin from the plugins list.
2. Select Download option from Bulk Actions drop-down.
3. Click on Apply Button.
4. It shows message----Pass
5. Message should display in Popup--Fail

**Comment by Myresearchergit** [comment]
It shows message as per previous task:
Please select a plugin (or multiple plugins) to begin download.

**Comment by Myresearchergit** [comment]
popup added, if no select any plugin from the plugins list.
