### ISSUE TITLE
Install and Activate Plugins option Verification in Popup View 3

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#10]
After selecting plugins, clicking on Install and Activate button on Popup view 3, plugins are not getting installed and we are getting this error everytime.
See screenshot: https://nimb.ws/UKRxeV

**Comment by Myresearchergit** [comment]
I request you to please check the issue in latest uploaded code if resolved. If still facing issue, please share the URL and credentials

**Comment by SakshiArora27** [comment]
https://s.nimbusweb.me/share/3118973/97bqpfld64lifxsmc7gr

**Comment by Myresearchergit** [comment]
resolved as mention in screenshot
