### ISSUE TITLE
On Click Button Verification on Plugins Page

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#11]
When we click on Multiple Upload Plugins button, page refreshes and redirects to another page where it shows Choose file option. It is working like this as of now.
Please refer this video: https://nimb.ws/duiDlm

Instead the page should not get refresh and should show choose file option on the same page itself. It should be same like the existing input file control which appears on clicking Upload Plugin.
Please refer video: https://nimb.ws/fb1dG0

**Comment by Myresearchergit** [comment]
Actually that area is used by wordpress default.  We are not able to insert HTML with default area.  So in case of multiple uploads page should be redirect to another page where our custom code initiate.
