### ISSUE TITLE
Text Verification on Plugins Page

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#13]
Please refer this screenshot: https://nimb.ws/uLbK1o

**Comment by Myresearchergit** [comment]
These are done:-
1). Title change 
2). Remove border
3). Change 'Activate button ' position

**Comment by Myresearchergit** [comment]
The text shown here is the browser default text.  We are not giving any text to display here.  So in chrome we are not able to change this text quickly.  It is browser default.
