### ISSUE TITLE
Installing Plugins Page Verification

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#14]
After installing plugins a new page will appear. Please made the following changes to this page: https://nimb.ws/jzIi3V

It should be appear like this(refer specs)
![plugins](https://user-images.githubusercontent.com/33451850/61950835-c08a7780-afcc-11e9-9c99-5cd1dd9daf6e.png)

**Comment by Myresearchergit** [comment]
These are done:-
1). Title change 
2). Remove border
3). Change 'Activate button ' position

**Comment by SakshiArora27** [comment]
All others are fine. This one is not resolved. Please check: https://nimb.ws/r3Ldoe

**Comment by Myresearchergit** [comment]
its done, please check

**Comment by SakshiArora27** [comment]
Please see screenshot: https://nimb.ws/aVZtPO

**Comment by Myresearchergit** [comment]
its done, please check
