### ISSUE TITLE
Boxes Width and Height Verification

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#15]
All boxes should have equal height and width. please refer this screenshot:
https://nimb.ws/lIw1zP

**Comment by Myresearchergit** [comment]
removed extra text and set box height equal, please check

**Comment by SakshiArora27** [comment]
Showing extra space in between. Please check: https://nimb.ws/PShtF7

**Comment by Myresearchergit** [comment]
this issue fixed at my end please check.

**Comment by SakshiArora27** [comment]
Fixed in chrome but extra spacing is appearing in firefox.

![FireShot Capture 002 - ‹ devptesting — WordPress - devpgtesting cmshelplive net](https://user-images.githubusercontent.com/33451850/62623982-b6a73380-b93f-11e9-9d5e-cc5819054d3f.png)

**Comment by Myresearchergit** [comment]
This is done and tested successfully on our end.  please check this now
