### ISSUE TITLE
Activate Plugin option Verification on  Installing Plugins Page

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#16]
Steps to Reproduce:
1. Install Multiple plugins.
2. After installing it redirects to installing plugins page with the boxes of plugins status.
3. After successfully installing of plugins it shows "Activate Plugin" button in respective boxes.
4. After clicking on Activate Plugin Button, it shows the popup on same page and as we click on OK
"Activate Plugin" text changes to "Plugin Activated" and box remains there on the page----Fail
Instead After clicking on "Activate Plugin" button, it should refresh the page and remove the specific plugin HTML box.

**Comment by Myresearchergit** [comment]
Currently we have using best approach to make this.  If we are refresh the page then it will generate some other issues that we know in mind.

So I can only do one thing is that I can hide the plugin that has been activated successfully without refreshing the page.

**Comment by SakshiArora27** [comment]
As discussed with @CharanS05  sir current functionality is fine and no changes are required here. So closing it.
