### ISSUE TITLE
Activate ALL Button Verification on Plugins Page

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#17]
Activate All button is of no use in these cases:

1. When all the selected plugins are not installed due to some errors then Activate Button should not appear. It should be hidden. Please refer this: https://nimb.ws/OA2LyI
After Clicking on Activate All it redirects to this page which is blank as none of the plugin is activated: https://nimb.ws/WtO7dZ

2. When single plugin is uploaded and failed: https://nimb.ws/JE6O37

@CharanS05 : Please check and suggest.

**Comment by Myresearchergit** [comment]
This is done. Please test and close.
