### ISSUE TITLE
Activation Status Page Verification

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#19]
Plugin name, Unpacking status, Installing status information is missing on activation status page.
Please refer screenshot: https://nimb.ws/TtfwiW
It should be like this: 
![Activation](https://user-images.githubusercontent.com/33451850/61991035-5c1cf600-b068-11e9-8b75-f89688129b9c.png)

**Comment by Myresearchergit** [comment]
Its done. Please check

**Comment by SakshiArora27** [comment]
2 issues are resolved. 3rd is still pending. Please check: https://nimb.ws/P2ejt7

**Comment by Myresearchergit** [comment]
fixed, text replaced with button
