### ISSUE TITLE
Multi Upload Functionality Verification

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#20]
When try to upload multiple plugins it always uploads 20 plugins.
For eg: I tried to upload 30 plugins but it shows 20 plugins only.

**Comment by Myresearchergit** [comment]
set max limit 20, please check

**Comment by Myresearchergit** [comment]
Hi Guys

Now user can able to UPLOAD max of 20 plugin at a time.  We have test this and working fine now.  Please test and share your feedback.

**Comment by SakshiArora27** [comment]
working now.
