### ISSUE TITLE
Issues in Mac

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#23]
1. While downloading plugins in Mac using safari browser, plugins get downloaded in folder instead of zip.

2. Issue is in Mac in all the browsers:
https://nimb.ws/pWDtGJ

**Comment by Myresearchergit** [comment]
Please share MAC and safari browser version on which you are doing testing

**Comment by Myresearchergit** [comment]
Hi Guys,

This is the default behavior of safari browser in MAC.  Please try to download some other zip file or wordpress.org official plugins/theme download.  It always download in unzip format.

Still wan to get rid on this then you need to follow below steps:
https://macreports.com/how-to-download-zip-files-without-unzipping/

**Comment by Myresearchergit** [comment]
Hi Guys,

This is the default behavior of safari browser in MAC.  Please try to download some other zip file or wordpress.org official plugins/theme download.  It always download in unzip format.

Still wan to get rid on this then you need to follow below steps:
https://macreports.com/how-to-download-zip-files-without-unzipping/
