### ISSUE TITLE
Multi Download Option Verification

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#3]
After downloading with multiple download option from Bulk action dropdown menu, if we refresh the page the plugins are downloaded again.

Please refer this Video: https://nimb.ws/qso90u

**Comment by Myresearchergit** [comment]
Actually when we are downloading the selected files then page URL has been modified with extra information through which downloadable script download the plugins.  So if someone again reload the page then same plugins will download again. This is default as user are on same URL.

But after downloading some plugins if user try to download another plugin then only selected plugins will be downloaded.  But page reload will download plugin again.

**Comment by SakshiArora27** [comment]
Working now.
