### ISSUE TITLE
Multi Download Functionality Verification

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#5]
Multi Download option is not working properly.
1. When multiple plugins are selected(5 or more) to download:
Then 1st time it downloads only 1 or 2 plugins and page goes on loading and nothing happens. 2nd time when try again to download then it works. It is behaving Randomly sometimes it works and sometimes not.

2. When All Plugins are selected and try to download it from bulk actions then it downloads only 1 or 2 plugins and page goes on loading and nothing happens.

**Comment by Myresearchergit** [comment]
Please check

**Comment by Myresearchergit** [comment]
Please use updated GIT code for check Multi Download Functionality.
Please check and let me know, how many plugins download at your end. 
We are still working on this point.

**Comment by SakshiArora27** [comment]
okay.

**Comment by SakshiArora27** [comment]
Out of 71 plugins 18 plugins are downloaded and then page goes on loading and then stops after few minutes.

**Comment by Myresearchergit** [comment]
Okay.  Let us allow to make more modification in our code.

**Comment by SakshiArora27** [comment]
okay.

**Comment by Myresearchergit** [comment]
We have make major changes with this part. Please test and share your feedback here.

**Comment by SakshiArora27** [comment]
Multi download functionality is still not working in chrome. It is showing Page Unresponsive error again and again and page goes on loading. Not a single plugin is downloaded.

**Comment by Myresearchergit** [comment]
set limit of 30 on multiple download, please check

**Comment by Myresearchergit** [comment]
Hi Guys

We have introduce limit now.  User can able to download max of 30 plugin at a time.  We have test this and working fine now.  Please test and share your feedback.
