### ISSUE TITLE
Multi-Upload Option Verification

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#6]
Multi-Upload functionality is not working. Button position is not correct and unable to upload multiple plugins.
Please refer this screenshot: https://nimb.ws/pz8ri7

**Comment by Myresearchergit** [comment]
Please check. If facing issue, please share the site URL and credentials

**Comment by SakshiArora27** [comment]
Still not working at my end. Seems to be a positioning issue of button. Please check here: 
https://devpgtesting.cmshelplive.net/wp-admin/
User: admin
Password: admin123!@#

**Comment by Myresearchergit** [comment]
Issue fixed, please check screenshot
https://www.awesomescreenshot.com/image/4146199/431f4218e0929913f669d68f52d6a27e
