### ISSUE TITLE
Popup Verification In Default View 1

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#7]
1. Image is not properly aligned and should cover whole area.
2. Title should be placed out of the image container.
3. Text is missing at the bottom in the left side. It should be this:

> Bottom:
> Left aligned Text:
> If you wish to know more about how to use these new features, please read our guide.
> Anchor text - read out guide
> Resource - https://metagauss.com/download-plugin-guide/

Please refer this screenshot: https://nimb.ws/6kFs9U

4. Close button in the specs given is out of the container. It is a generic issue and should be apply to all popup views.

**Comment by Myresearchergit** [comment]
Done, please check

**Comment by SakshiArora27** [comment]
Please refer this: https://nimb.ws/ODjCxf

**Comment by SakshiArora27** [comment]
Link should redirect to: https://metagauss.com/download-plugin-guide/

**Comment by Myresearchergit** [comment]
Link added to read our guide
