### ISSUE TITLE
Popup Verification in View 2

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#8]
Please refer this screenshot: https://nimb.ws/EG7N6Q

**Comment by Myresearchergit** [comment]
Please check the last commit

**Comment by SakshiArora27** [comment]
Please see screenshot: https://nimb.ws/HQYRSt

**Comment by SakshiArora27** [comment]
When we select few options from popup view 2 and click on next it shows the results on same screen for few seconds and then shows popup 3.  
Please refer this video: https://nimb.ws/zt7ZbO

**Comment by Myresearchergit** [comment]
Make changes, now it showing "Please wait..." message before load next section

**Comment by SakshiArora27** [comment]
Colon(:) and left spacing is missing in the top text: https://nimb.ws/HQYRSt
when we click on back button then plugin displays for few seconds at bottom.
Please check this video: https://nimb.ws/rZ3Jmx

**Comment by Myresearchergit** [comment]
This is fix. Please test and close.
