### ISSUE TITLE
Popup Verification in View 3

### ISSUE THREAD

**Issue by SakshiArora27** [alcanttor/Download-Plugin#9]
Popup Verification in view 3:
https://nimb.ws/N3xfHR

Refer specs for more clarification.

**Comment by Myresearchergit** [comment]
Done, please check

**Comment by SakshiArora27** [comment]
Please refer this: https://nimb.ws/6NPm0A

**Comment by Myresearchergit** [comment]
I make this change. Please check below screenshot.
https://www.awesomescreenshot.com/image/4146145/a73a46ba7a19bb64b540d5e02d531072
